# This file was generated by GoReleaser. DO NOT EDIT.
class ChartReleaser < Formula
  desc "CI tool for automating Helm Chart version bumps on new app release"
  homepage "https://github.com/edaniszewski/chart-releaser"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/edaniszewski/chart-releaser/releases/download/0.1.2/chart-releaser_darwin_amd64.tar.gz"
    sha256 "d19dbde054ccc532390ad7c8bdba15871d5fe0ec00dd92d647144f69cd51c87d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/edaniszewski/chart-releaser/releases/download/0.1.2/chart-releaser_linux_amd64.tar.gz"
      sha256 "691a60c6c3289cf22825a5509e8df9f4265ffb0b4f4a68dfe128e7229407a8a3"
    end
  end

  def install
    bin.install "chart-releaser"
  end

  test do
    system "#{bin}/chart-releaser version"
  end
end
