# This file was generated by GoReleaser. DO NOT EDIT.
class ChartReleaser < Formula
  desc "CI tool for automating Helm Chart version bumps on new app release"
  homepage "https://github.com/edaniszewski/chart-releaser"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/edaniszewski/chart-releaser/releases/download/0.1.0/chart-releaser_darwin_amd64.tar.gz"
    sha256 "d0609ec1e6067b92cd5264d28b43ff61a7bc50c252649fb663bd751af800e1e5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/edaniszewski/chart-releaser/releases/download/0.1.0/chart-releaser_linux_amd64.tar.gz"
      sha256 "4e1272237eee4e9e355f7f457387f68a473c99ceb781effad42716b9ff7d93d2"
    end
  end

  def install
    bin.install "chart-releaser"
  end

  test do
    system "#{bin}/chart-releaser version"
  end
end
