# This file was generated by GoReleaser. DO NOT EDIT.
class Envsnap < Formula
  desc "Project-defined user environment snapshots for debugging and reporting"
  homepage "https://github.com/edaniszewski/envsnap"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/edaniszewski/envsnap/releases/download/0.1.3/envsnap_darwin_amd64.tar.gz"
    sha256 "6b4173ac9796b6da39db0dc02dec656a02bb920b32d5e103f12add4971f77b7e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/edaniszewski/envsnap/releases/download/0.1.3/envsnap_linux_amd64.tar.gz"
      sha256 "7f4738b97ae2439b813cf7e0804da0b55fa79b28e0e3262aae0ac81ff7793fa8"
    end
  end

  def install
    bin.install "envsnap"
  end

  test do
    system "#{bin}/envsnap --version"
  end
end
